// ============================================================================
// NexMart — Mock Data & Constants
// Comprehensive mock data so the app works standalone without backend
// ============================================================================

// ── Navigation Categories ──────────────────────────────────────────────
export const NAV_CATEGORIES = [
  { name: 'Electronics', slug: 'electronics', icon: '📱', emoji: '📱' },
  { name: 'Fashion', slug: 'fashion', icon: '👗', emoji: '👗' },
  { name: 'Home & Kitchen', slug: 'home-kitchen', icon: '🏠', emoji: '🏠' },
  { name: 'Beauty', slug: 'beauty', icon: '💄', emoji: '💄' },
  { name: 'Sports', slug: 'sports', icon: '🏃', emoji: '🏃' },
  { name: 'Books', slug: 'books', icon: '📚', emoji: '📚' },
  { name: 'Toys & Games', slug: 'toys-games', icon: '🎮', emoji: '🎮' },
  { name: 'Grocery', slug: 'grocery', icon: '🛒', emoji: '🛒' },
  { name: 'Deals', slug: 'deals', icon: '⚡', emoji: '⚡', isHighlighted: true },
];

export const CATEGORIES = NAV_CATEGORIES;

// ── Homepage Banners ────────────────────────────────────────────────────
export const HERO_BANNERS = [
  {
    id: '1',
    title: 'Electronics Mega Sale',
    subtitle: 'Up to 60% off on top brands',
    cta: 'Shop Now',
    ctaLink: '/category/electronics',
    image: 'https://picsum.photos/seed/banner-electronics/1200/400',
    bgGradient: 'from-indigo-600 to-purple-700',
  },
  {
    id: '2',
    title: 'Fashion Week Special',
    subtitle: 'New arrivals from ₹299',
    cta: 'Explore',
    ctaLink: '/category/fashion',
    image: 'https://picsum.photos/seed/banner-fashion/1200/400',
    bgGradient: 'from-pink-500 to-rose-600',
  },
  {
    id: '3',
    title: 'NexMart Plus Launch',
    subtitle: 'Free delivery + early access for ₹299/month',
    cta: 'Join Now',
    ctaLink: '/nexmart-plus',
    image: 'https://picsum.photos/seed/banner-plus/1200/400',
    bgGradient: 'from-amber-500 to-orange-600',
  },
  {
    id: '4',
    title: 'Home Makeover Festival',
    subtitle: 'Furniture, decor & appliances from ₹499',
    cta: 'Shop Home',
    ctaLink: '/category/home-kitchen',
    image: 'https://picsum.photos/seed/banner-home/1200/400',
    bgGradient: 'from-emerald-500 to-teal-600',
  },
];

// ── Brand Logos ────────────────────────────────────────────────────────
export const BRANDS = [
  { name: 'Apple', logo: 'https://picsum.photos/seed/apple-logo/120/60' },
  { name: 'Samsung', logo: 'https://picsum.photos/seed/samsung-logo/120/60' },
  { name: 'Nike', logo: 'https://picsum.photos/seed/nike-logo/120/60' },
  { name: 'Adidas', logo: 'https://picsum.photos/seed/adidas-logo/120/60' },
  { name: 'Sony', logo: 'https://picsum.photos/seed/sony-logo/120/60' },
  { name: 'LG', logo: 'https://picsum.photos/seed/lg-logo/120/60' },
  { name: 'Puma', logo: 'https://picsum.photos/seed/puma-logo/120/60' },
  { name: 'Boat', logo: 'https://picsum.photos/seed/boat-logo/120/60' },
  { name: 'Lakme', logo: 'https://picsum.photos/seed/lakme-logo/120/60' },
  { name: 'Titan', logo: 'https://picsum.photos/seed/titan-logo/120/60' },
];

// ── Mock Products ───────────────────────────────────────────────────────
export interface MockProduct {
  id: string;
  name: string;
  slug: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  mrp: number;
  rating: number;
  reviewCount: number;
  image: string;
  images: string[];
  badges: Array<{ text: string; type: 'sale' | 'new' | 'bestseller' | 'choice' }>;
  freeDelivery: boolean;
  inStock: boolean;
  isFulfilledByNexmart: boolean;
  description: string;
  shortDescription: string;
  highlights: string[];
  sizes?: string[];
  colors?: Array<{ name: string; hex: string }>;
  specs?: Record<string, string>;
  manufacturingDetails: {
    countryOfOrigin: string;
    material?: string;
    weight?: string;
    dimensions?: string;
  };
  vendorName: string;
  vendorRating: number;
}

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: 'prod-001',
    name: 'Samsung Galaxy S24 Ultra 256GB',
    slug: 'samsung-galaxy-s24-ultra-256gb',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 129999,
    mrp: 134999,
    rating: 4.6,
    reviewCount: 8432,
    image: 'https://picsum.photos/seed/samsung-s24/400/400',
    images: [
      'https://picsum.photos/seed/samsung-s24-1/600/600',
      'https://picsum.photos/seed/samsung-s24-2/600/600',
      'https://picsum.photos/seed/samsung-s24-3/600/600',
      'https://picsum.photos/seed/samsung-s24-4/600/600',
      'https://picsum.photos/seed/samsung-s24-5/600/600',
    ],
    badges: [{ text: 'BESTSELLER', type: 'bestseller' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: true,
    description: 'The Samsung Galaxy S24 Ultra redefines what a smartphone can do. Powered by the Snapdragon 8 Gen 3 processor, it delivers blazing-fast performance for gaming, multitasking, and AI-powered features. The 6.8-inch Dynamic AMOLED 2X display with 2600 nits peak brightness makes everything look stunning, whether you\'re watching movies or editing photos. The quad-camera system featuring a 200MP main sensor captures incredible detail, and the built-in S Pen lets you sketch, annotate, and navigate with precision. With Galaxy AI features like Circle to Search, Live Translate, and Chat Assist, this phone truly feels like the future.',
    shortDescription: 'Flagship smartphone with 200MP camera, Snapdragon 8 Gen 3, S Pen, and Galaxy AI features.',
    highlights: [
      '200MP quad-camera with Nightography',
      'Snapdragon 8 Gen 3 processor',
      '6.8" Dynamic AMOLED 2X display (2600 nits)',
      'Built-in S Pen with AI features',
      '5000mAh battery with 45W fast charging',
    ],
    sizes: ['128GB', '256GB', '512GB', '1TB'],
    colors: [
      { name: 'Titanium Black', hex: '#1A1A1A' },
      { name: 'Titanium Gray', hex: '#8B8B8B' },
      { name: 'Titanium Violet', hex: '#9B59B6' },
      { name: 'Titanium Yellow', hex: '#F1C40F' },
    ],
    specs: {
      'Processor': 'Snapdragon 8 Gen 3',
      'Display': '6.8" Dynamic AMOLED 2X',
      'RAM': '12GB',
      'Storage': '256GB',
      'Camera': '200MP + 50MP + 12MP + 10MP',
      'Battery': '5000mAh',
      'OS': 'Android 14 (One UI 6.1)',
    },
    manufacturingDetails: {
      countryOfOrigin: 'South Korea',
      material: 'Titanium, Glass',
      weight: '232g',
      dimensions: '162.3 x 79 x 8.6 mm',
    },
    vendorName: 'Samsung Official',
    vendorRating: 4.8,
  },
  {
    id: 'prod-002',
    name: 'Apple MacBook Air M3 13-inch',
    slug: 'apple-macbook-air-m3-13',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Laptops',
    price: 114990,
    mrp: 129990,
    rating: 4.8,
    reviewCount: 2341,
    image: 'https://picsum.photos/seed/macbook-air-m3/400/400',
    images: [
      'https://picsum.photos/seed/macbook-m3-1/600/600',
      'https://picsum.photos/seed/macbook-m3-2/600/600',
      'https://picsum.photos/seed/macbook-m3-3/600/600',
      'https://picsum.photos/seed/macbook-m3-4/600/600',
      'https://picsum.photos/seed/macbook-m3-5/600/600',
    ],
    badges: [{ text: 'NexMart\'s Choice', type: 'choice' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: true,
    description: 'The MacBook Air with M3 chip is Apple\'s most capable thin and light laptop. The M3 chip brings faster CPU, GPU, and Neural Engine performance, enabling smooth multitasking and creative workflows. The stunning 13.6-inch Liquid Retina display supports 1 billion colors and 500 nits brightness. With up to 18 hours of battery life, MagSafe charging, a 1080p FaceTime HD camera, and a four-speaker sound system with Spatial Audio, this laptop is perfect for professionals and students alike. The fanless design means it runs completely silent, and it weighs just 1.24 kg.',
    shortDescription: 'Ultra-thin laptop with Apple M3 chip, 18-hour battery, and stunning Liquid Retina display.',
    highlights: [
      'Apple M3 chip — 8-core CPU, 10-core GPU',
      '13.6" Liquid Retina display (500 nits, P3 wide color)',
      'Up to 18 hours battery life',
      'Fanless, silent design — 1.24 kg',
      'MagSafe charging + 2 Thunderbolt ports',
    ],
    sizes: ['256GB', '512GB', '1TB'],
    colors: [
      { name: 'Space Gray', hex: '#555555' },
      { name: 'Silver', hex: '#C0C0C0' },
      { name: 'Starlight', hex: '#F5E6D3' },
      { name: 'Midnight', hex: '#1D1D2C' },
    ],
    specs: {
      'Processor': 'Apple M3',
      'Display': '13.6" Liquid Retina',
      'RAM': '8GB Unified Memory',
      'Storage': '256GB SSD',
      'Battery': 'Up to 18 hours',
      'Weight': '1.24 kg',
    },
    manufacturingDetails: {
      countryOfOrigin: 'China',
      material: 'Aluminum',
      weight: '1.24 kg',
      dimensions: '304.1 x 215 x 11.3 mm',
    },
    vendorName: 'Apple India',
    vendorRating: 4.9,
  },
  {
    id: 'prod-003',
    name: 'Nike Air Max 270 React',
    slug: 'nike-air-max-270-react',
    brand: 'Nike',
    category: 'Fashion',
    subcategory: 'Sneakers',
    price: 4999,
    mrp: 8499,
    rating: 4.4,
    reviewCount: 4231,
    image: 'https://picsum.photos/seed/nike-airmax/400/400',
    images: [
      'https://picsum.photos/seed/nike-am-1/600/600',
      'https://picsum.photos/seed/nike-am-2/600/600',
      'https://picsum.photos/seed/nike-am-3/600/600',
      'https://picsum.photos/seed/nike-am-4/600/600',
      'https://picsum.photos/seed/nike-am-5/600/600',
    ],
    badges: [{ text: 'SALE -41%', type: 'sale' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: false,
    description: 'The Nike Air Max 270 React combines two of Nike\'s best technologies for unbelievable comfort and style. The Air Max 270 heel unit provides maximum cushioning while the React foam midsole delivers an incredibly soft and responsive ride. The mesh upper keeps your feet cool and breathable, perfect for the Indian climate. Whether you\'re heading to college, hitting the gym, or just stepping out in style, these sneakers make a statement. The rubber outsole provides excellent traction on various surfaces, and the pull tab at the heel makes them easy to slip on.',
    shortDescription: 'Iconic lifestyle sneakers with Air Max 270 cushioning and React foam comfort.',
    highlights: [
      'Air Max 270 heel unit for maximum cushioning',
      'React foam midsole — soft & responsive',
      'Breathable mesh upper',
      'Durable rubber outsole',
      'Iconic Nike design',
    ],
    sizes: ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
    colors: [
      { name: 'Black/White', hex: '#1A1A1A' },
      { name: 'White/Red', hex: '#FFFFFF' },
      { name: 'Navy Blue', hex: '#1B2A4A' },
    ],
    specs: {
      'Upper': 'Mesh, Synthetic',
      'Midsole': 'React Foam + Air Max 270',
      'Outsole': 'Rubber',
      'Closure': 'Lace-up',
    },
    manufacturingDetails: {
      countryOfOrigin: 'Vietnam',
      material: 'Mesh, Synthetic, Rubber',
      weight: '310g (per shoe, UK 9)',
    },
    vendorName: 'Nike Official',
    vendorRating: 4.7,
  },
  {
    id: 'prod-004',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    slug: 'sony-wh-1000xm5',
    brand: 'Sony',
    category: 'Electronics',
    subcategory: 'Headphones',
    price: 24990,
    mrp: 29990,
    rating: 4.7,
    reviewCount: 5621,
    image: 'https://picsum.photos/seed/sony-xm5/400/400',
    images: [
      'https://picsum.photos/seed/sony-xm5-1/600/600',
      'https://picsum.photos/seed/sony-xm5-2/600/600',
      'https://picsum.photos/seed/sony-xm5-3/600/600',
      'https://picsum.photos/seed/sony-xm5-4/600/600',
      'https://picsum.photos/seed/sony-xm5-5/600/600',
    ],
    badges: [{ text: 'BESTSELLER', type: 'bestseller' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: true,
    description: 'The Sony WH-1000XM5 is the gold standard for wireless noise-cancelling headphones. With two processors controlling eight microphones, the noise cancellation is best-in-class, letting you focus on your music, podcasts, or calls without distraction. The 30mm drivers deliver exceptional audio quality with rich bass and crystal-clear highs. Multipoint connection lets you switch seamlessly between your phone and laptop. With 30 hours of battery life, ultra-fast charging (3 min for 3 hours), and Speak-to-Chat auto-pause, these headphones are designed for all-day comfort and convenience.',
    shortDescription: 'Industry-leading ANC headphones with 30hr battery, multipoint, and exceptional sound quality.',
    highlights: [
      'Industry-leading noise cancellation with Auto NC Optimizer',
      '30 hours battery, 3-min quick charge for 3 hours',
      'Multipoint connection (2 devices simultaneously)',
      'Speak-to-Chat auto-pause technology',
      'Ultra-comfortable lightweight design (250g)',
    ],
    colors: [
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Silver', hex: '#C0C0C0' },
    ],
    specs: {
      'Driver': '30mm',
      'ANC': 'Dual Processor, 8 mics',
      'Battery': '30 hours',
      'Bluetooth': '5.3',
      'Weight': '250g',
      'Codecs': 'LDAC, AAC, SBC',
    },
    manufacturingDetails: {
      countryOfOrigin: 'Malaysia',
      material: 'Plastic, Synthetic Leather, Metal',
      weight: '250g',
    },
    vendorName: 'Sony India',
    vendorRating: 4.8,
  },
  {
    id: 'prod-005',
    name: 'Prestige Omega Deluxe Induction Base Non-Stick Kitchen Set',
    slug: 'prestige-omega-deluxe-kitchen-set',
    brand: 'Prestige',
    category: 'Home & Kitchen',
    subcategory: 'Cookware',
    price: 2499,
    mrp: 4995,
    rating: 4.3,
    reviewCount: 12450,
    image: 'https://picsum.photos/seed/prestige-kitchen/400/400',
    images: [
      'https://picsum.photos/seed/prestige-1/600/600',
      'https://picsum.photos/seed/prestige-2/600/600',
      'https://picsum.photos/seed/prestige-3/600/600',
      'https://picsum.photos/seed/prestige-4/600/600',
      'https://picsum.photos/seed/prestige-5/600/600',
    ],
    badges: [{ text: 'SALE -50%', type: 'sale' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: true,
    description: 'The Prestige Omega Deluxe Kitchen Set is a complete non-stick cooking solution for Indian kitchens. This 3-piece set includes a fry pan, tawa, and kadhai — the essentials for everyday Indian cooking from rotis to curries. The premium Granite non-stick coating is PFOA-free and provides excellent food release, making cooking and cleaning effortless. The heavy-gauge aluminum base ensures even heat distribution, and the induction-compatible base works on all cooktops. The stay-cool handles provide a safe, comfortable grip even during extended cooking sessions.',
    shortDescription: '3-piece non-stick cookware set with granite coating, induction base. Perfect for Indian kitchens.',
    highlights: [
      '3-piece set: Fry Pan, Tawa, Kadhai',
      'Premium granite non-stick coating (PFOA-free)',
      'Induction base compatible — works on all cooktops',
      'Heavy-gauge aluminum for even heat distribution',
      'Cool-touch handles for safe grip',
    ],
    specs: {
      'Set Contents': 'Fry Pan 24cm, Tawa 28cm, Kadhai 24cm',
      'Material': 'Aluminium',
      'Coating': 'Granite Non-Stick',
      'Induction': 'Yes',
    },
    manufacturingDetails: {
      countryOfOrigin: 'India',
      material: 'Aluminium, Non-stick coating',
      weight: '2.1 kg (set)',
    },
    vendorName: 'Prestige Store',
    vendorRating: 4.5,
  },
  {
    id: 'prod-006',
    name: 'Levi\'s Men 511 Slim Fit Jeans',
    slug: 'levis-511-slim-fit-jeans',
    brand: 'Levi\'s',
    category: 'Fashion',
    subcategory: 'Jeans',
    price: 1799,
    mrp: 3599,
    rating: 4.3,
    reviewCount: 7823,
    image: 'https://picsum.photos/seed/levis-511/400/400',
    images: [
      'https://picsum.photos/seed/levis-1/600/600',
      'https://picsum.photos/seed/levis-2/600/600',
      'https://picsum.photos/seed/levis-3/600/600',
      'https://picsum.photos/seed/levis-4/600/600',
      'https://picsum.photos/seed/levis-5/600/600',
    ],
    badges: [{ text: 'SALE -50%', type: 'sale' }],
    freeDelivery: false,
    inStock: true,
    isFulfilledByNexmart: false,
    description: 'The Levi\'s 511 Slim Fit Jeans are the perfect blend of classic Levi\'s quality and modern slim styling. Cut to sit below the waist with a slim fit through the hip and thigh, these jeans are versatile enough for work, weekends, or a night out. Made from premium cotton denim with a touch of elastane for comfortable stretch, they move with you throughout the day. The signature Levi\'s arcuate stitching on the back pockets and the iconic red tab make these instantly recognizable. Available in a range of washes to suit every style preference.',
    shortDescription: 'Classic slim fit jeans with stretch comfort and iconic Levi\'s quality.',
    highlights: [
      'Slim fit through hip and thigh',
      'Premium cotton denim with elastane stretch',
      'Classic 5-pocket styling',
      'Iconic Levi\'s red tab and arcuate stitching',
      'Machine washable',
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: [
      { name: 'Dark Indigo', hex: '#1E3A5F' },
      { name: 'Mid Blue', hex: '#4A90D9' },
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Grey', hex: '#6B7280' },
    ],
    specs: {
      'Fit': 'Slim',
      'Rise': 'Mid Rise',
      'Fabric': '98% Cotton, 2% Elastane',
      'Care': 'Machine Wash Cold',
    },
    manufacturingDetails: {
      countryOfOrigin: 'Bangladesh',
      material: 'Cotton, Elastane',
      weight: '450g',
    },
    vendorName: 'Levi\'s Official',
    vendorRating: 4.6,
  },
  {
    id: 'prod-007',
    name: 'boAt Rockerz 450 Bluetooth Headphones',
    slug: 'boat-rockerz-450',
    brand: 'boAt',
    category: 'Electronics',
    subcategory: 'Headphones',
    price: 1099,
    mrp: 2990,
    rating: 4.1,
    reviewCount: 34521,
    image: 'https://picsum.photos/seed/boat-450/400/400',
    images: [
      'https://picsum.photos/seed/boat-1/600/600',
      'https://picsum.photos/seed/boat-2/600/600',
      'https://picsum.photos/seed/boat-3/600/600',
      'https://picsum.photos/seed/boat-4/600/600',
      'https://picsum.photos/seed/boat-5/600/600',
    ],
    badges: [{ text: 'SALE -63%', type: 'sale' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: true,
    description: 'The boAt Rockerz 450 delivers premium audio quality at an incredible price. With 40mm dynamic drivers pumping out powerful bass and clear mids, your music comes alive. The padded ear cushions and adjustable headband provide hours of comfortable listening. With 15 hours of battery life, Bluetooth 4.2, and a foldable design, these are perfect for your daily commute, workouts, or study sessions. The built-in microphone lets you take calls hands-free, and the physical controls on the earcup give you easy access to volume, tracks, and play/pause.',
    shortDescription: 'Powerful bass headphones with 15hr battery, foldable design at an unbeatable price.',
    highlights: [
      '40mm dynamic drivers for powerful bass',
      '15 hours battery life',
      'Padded ear cushions — all-day comfort',
      'Foldable design — easy to carry',
      'Built-in mic for hands-free calls',
    ],
    colors: [
      { name: 'Luscious Black', hex: '#1A1A1A' },
      { name: 'Aqua Blue', hex: '#00BCD4' },
      { name: 'Hazel Beige', hex: '#D4A574' },
    ],
    specs: {
      'Driver': '40mm',
      'Battery': '15 hours',
      'Bluetooth': '4.2',
      'Weight': '180g',
    },
    manufacturingDetails: {
      countryOfOrigin: 'China',
      material: 'Plastic, Leatherette',
      weight: '180g',
    },
    vendorName: 'boAt Lifestyle',
    vendorRating: 4.3,
  },
  {
    id: 'prod-008',
    name: 'Mamaearth Vitamin C Face Wash',
    slug: 'mamaearth-vitamin-c-face-wash',
    brand: 'Mamaearth',
    category: 'Beauty',
    subcategory: 'Skincare',
    price: 299,
    mrp: 499,
    rating: 4.2,
    reviewCount: 18234,
    image: 'https://picsum.photos/seed/mamaearth-vit-c/400/400',
    images: [
      'https://picsum.photos/seed/mamaearth-1/600/600',
      'https://picsum.photos/seed/mamaearth-2/600/600',
      'https://picsum.photos/seed/mamaearth-3/600/600',
      'https://picsum.photos/seed/mamaearth-4/600/600',
      'https://picsum.photos/seed/mamaearth-5/600/600',
    ],
    badges: [{ text: 'BESTSELLER', type: 'bestseller' }],
    freeDelivery: false,
    inStock: true,
    isFulfilledByNexmart: false,
    description: 'The Mamaearth Vitamin C Face Wash is your daily companion for bright, glowing skin. Enriched with Vitamin C and Turmeric, this face wash gently cleanses while boosting radiance and evening out skin tone. The natural, toxin-free formula is free from sulfates, parabens, SLS, and artificial colors. Suitable for all skin types, it effectively removes dirt, oil, and impurities without stripping your skin of its natural moisture. Made with the goodness of nature, this face wash is dermatologically tested and safe for daily use.',
    shortDescription: 'Natural Vitamin C face wash with Turmeric for bright, glowing skin. Toxin-free formula.',
    highlights: [
      'Vitamin C + Turmeric for skin brightening',
      'Sulfate-free, Paraben-free, SLS-free',
      'Suitable for all skin types',
      'Dermatologically tested',
      'Made with natural ingredients',
    ],
    sizes: ['100ml', '150ml', '250ml'],
    specs: {
      'Type': 'Face Wash',
      'Key Ingredients': 'Vitamin C, Turmeric',
      'Skin Type': 'All Skin Types',
      'Paraben Free': 'Yes',
    },
    manufacturingDetails: {
      countryOfOrigin: 'India',
      material: 'Natural ingredients',
      weight: '150ml',
    },
    vendorName: 'Mamaearth Official',
    vendorRating: 4.4,
  },
  {
    id: 'prod-009',
    name: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    slug: 'ikigai-japanese-secret',
    brand: 'Penguin',
    category: 'Books',
    subcategory: 'Self-Help',
    price: 199,
    mrp: 350,
    rating: 4.5,
    reviewCount: 45200,
    image: 'https://picsum.photos/seed/ikigai-book/400/400',
    images: [
      'https://picsum.photos/seed/ikigai-1/600/600',
      'https://picsum.photos/seed/ikigai-2/600/600',
      'https://picsum.photos/seed/ikigai-3/600/600',
      'https://picsum.photos/seed/ikigai-4/600/600',
      'https://picsum.photos/seed/ikigai-5/600/600',
    ],
    badges: [{ text: 'BESTSELLER', type: 'bestseller' }],
    freeDelivery: false,
    inStock: true,
    isFulfilledByNexmart: false,
    description: 'Ikigai reveals the secrets to longevity and happiness from the Japanese island of Okinawa, home to the world\'s longest-living people. Authors Héctor García and Francesc Miralles share powerful insights into finding your purpose, nurturing relationships, staying active, eating well, and embracing the simple joys of life. Drawing on interviews with centenarians, this beautifully written book offers practical wisdom for living a meaningful, fulfilling life. Whether you\'re searching for your calling or looking to add more intention to your days, Ikigai will inspire and guide you toward a life worth living.',
    shortDescription: 'The international bestseller on finding your life purpose, based on Japanese wisdom from Okinawa.',
    highlights: [
      'International bestseller — 3M+ copies sold worldwide',
      'Insights from Okinawa\'s centenarians',
      'Practical tips for finding purpose & meaning',
      'Beautiful, easy-to-read format',
      'Perfect gift for self-improvement enthusiasts',
    ],
    specs: {
      'Pages': '208',
      'Language': 'English',
      'Publisher': 'Penguin Books',
      'Format': 'Paperback',
    },
    manufacturingDetails: {
      countryOfOrigin: 'India',
      weight: '180g',
      dimensions: '18 x 11 x 1.5 cm',
    },
    vendorName: 'BookWorld',
    vendorRating: 4.6,
  },
  {
    id: 'prod-010',
    name: 'JENGA Classic Game',
    slug: 'jenga-classic-game',
    brand: 'Hasbro',
    category: 'Toys & Games',
    subcategory: 'Board Games',
    price: 549,
    mrp: 999,
    rating: 4.4,
    reviewCount: 6780,
    image: 'https://picsum.photos/seed/jenga-game/400/400',
    images: [
      'https://picsum.photos/seed/jenga-1/600/600',
      'https://picsum.photos/seed/jenga-2/600/600',
      'https://picsum.photos/seed/jenga-3/600/600',
      'https://picsum.photos/seed/jenga-4/600/600',
      'https://picsum.photos/seed/jenga-5/600/600',
    ],
    badges: [{ text: 'SALE -45%', type: 'sale' }],
    freeDelivery: false,
    inStock: true,
    isFulfilledByNexmart: false,
    description: 'The classic Jenga game delivers edge-of-your-seat excitement that never gets old! Stack the wooden blocks into a sturdy tower, then take turns pulling out blocks one at a time. Can you carefully slide out a block without toppling the tower? The suspense builds with every move — will it crash on your turn? Made from genuine hardwood blocks, this is a game the whole family can enjoy. Perfect for parties, family game nights, or just a fun afternoon with friends. Simple to learn, impossible to master, and guaranteed to bring laughter and thrills.',
    shortDescription: 'The original block-stacking, tower-tumbling game for the whole family.',
    highlights: [
      '54 genuine hardwood Jenga blocks',
      'Stacking sleeve for easy cleanup',
      'For 1 or more players, ages 6+',
      'Perfect for parties and family game nights',
      'Simple rules — fun for all ages',
    ],
    specs: {
      'Players': '1+',
      'Age': '6+',
      'Blocks': '54 hardwood blocks',
      'Includes': 'Blocks + stacking sleeve',
    },
    manufacturingDetails: {
      countryOfOrigin: 'China',
      material: 'Hardwood',
      weight: '800g',
      dimensions: '28 x 8 x 8 cm (built tower)',
    },
    vendorName: 'ToyZone India',
    vendorRating: 4.3,
  },
  {
    id: 'prod-011',
    name: 'Apple iPhone 15 Pro 128GB',
    slug: 'apple-iphone-15-pro-128gb',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Smartphones',
    price: 134900,
    mrp: 134900,
    rating: 4.7,
    reviewCount: 6200,
    image: 'https://picsum.photos/seed/iphone15pro/400/400',
    images: [
      'https://picsum.photos/seed/iphone15-1/600/600',
      'https://picsum.photos/seed/iphone15-2/600/600',
      'https://picsum.photos/seed/iphone15-3/600/600',
      'https://picsum.photos/seed/iphone15-4/600/600',
      'https://picsum.photos/seed/iphone15-5/600/600',
    ],
    badges: [{ text: 'NEW', type: 'new' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: true,
    description: 'The iPhone 15 Pro features the new A17 Pro chip, the most powerful chip ever in a smartphone. The titanium design is strong yet lightweight, with a stunning 6.1-inch Super Retina XDR display that supports ProMotion 120Hz for smooth scrolling. The pro camera system includes a 48MP main camera with a new 5x optical zoom telephoto, capturing incredible detail in any lighting. Action Mode smooths video, and USB-C with USB 3 speeds makes transferring large files blazingly fast. With all-day battery life and iOS 17, this is the ultimate iPhone experience.',
    shortDescription: 'Titanium design, A17 Pro chip, 48MP camera with 5x zoom, USB-C.',
    highlights: [
      'A17 Pro chip — the most powerful smartphone chip',
      'Titanium design — strong yet lightweight',
      '48MP camera with 5x optical zoom',
      'USB-C with USB 3 transfer speeds',
      'All-day battery with MagSafe charging',
    ],
    sizes: ['128GB', '256GB', '512GB', '1TB'],
    colors: [
      { name: 'Natural Titanium', hex: '#A0A0A0' },
      { name: 'Blue Titanium', hex: '#4A6FA5' },
      { name: 'White Titanium', hex: '#E8E8E8' },
      { name: 'Black Titanium', hex: '#2C2C2E' },
    ],
    specs: {
      'Chip': 'A17 Pro',
      'Display': '6.1" Super Retina XDR',
      'Camera': '48MP Main + 12MP Ultra Wide + 12MP 5x Telephoto',
      'Battery': 'All-day battery',
      'Port': 'USB-C (USB 3)',
    },
    manufacturingDetails: {
      countryOfOrigin: 'China',
      material: 'Titanium, Ceramic Shield glass',
      weight: '187g',
      dimensions: '146.6 x 70.6 x 8.25 mm',
    },
    vendorName: 'Apple India',
    vendorRating: 4.9,
  },
  {
    id: 'prod-012',
    name: 'Wildcraft Unisex Travel Backpack 45L',
    slug: 'wildcraft-travel-backpack-45l',
    brand: 'Wildcraft',
    category: 'Sports',
    subcategory: 'Outdoor Gear',
    price: 2699,
    mrp: 4999,
    rating: 4.3,
    reviewCount: 3421,
    image: 'https://picsum.photos/seed/wildcraft-bag/400/400',
    images: [
      'https://picsum.photos/seed/wildcraft-1/600/600',
      'https://picsum.photos/seed/wildcraft-2/600/600',
      'https://picsum.photos/seed/wildcraft-3/600/600',
      'https://picsum.photos/seed/wildcraft-4/600/600',
      'https://picsum.photos/seed/wildcraft-5/600/600',
    ],
    badges: [{ text: 'SALE -46%', type: 'sale' }],
    freeDelivery: true,
    inStock: true,
    isFulfilledByNexmart: false,
    description: 'The Wildcraft 45L Travel Backpack is designed for adventurers who need a durable, spacious, and organized bag for trekking, camping, or weekend getaways. The main compartment easily fits 3-4 days of clothing and gear, while multiple external pockets keep smaller items accessible. The ergonomic back panel and padded shoulder straps distribute weight evenly for long-haul comfort. Rain cover included for monsoon protection. Made from tough 600D polyester, this backpack handles rough terrain and unpredictable weather with ease.',
    shortDescription: '45L travel backpack with rain cover, ergonomic design. Perfect for trekking and travel.',
    highlights: [
      '45L capacity — fits 3-4 days of gear',
      'Included rain cover for monsoon protection',
      'Ergonomic back panel + padded straps',
      '600D polyester — tough and durable',
      'Multiple compartments for organization',
    ],
    colors: [
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Navy', hex: '#1B2A4A' },
      { name: 'Red', hex: '#DC2626' },
    ],
    specs: {
      'Capacity': '45 Liters',
      'Material': '600D Polyester',
      'Rain Cover': 'Included',
      'Laptop Sleeve': 'Yes (up to 15.6")',
    },
    manufacturingDetails: {
      countryOfOrigin: 'India',
      material: '600D Polyester',
      weight: '1.2 kg',
      dimensions: '60 x 35 x 25 cm',
    },
    vendorName: 'Wildcraft India',
    vendorRating: 4.4,
  },
  // Additional products to fill out the grid
  ...generateAdditionalProducts(),
];

function generateAdditionalProducts(): MockProduct[] {
  const additional: MockProduct[] = [];
  const items = [
    { name: 'OnePlus 12 5G', brand: 'OnePlus', cat: 'Electronics', sub: 'Smartphones', p: 64999, m: 69999, r: 4.5, rc: 5432, slug: 'oneplus-12-5g' },
    { name: 'HP Pavilion 15 Laptop', brand: 'HP', cat: 'Electronics', sub: 'Laptops', p: 54990, m: 64990, r: 4.2, rc: 2100, slug: 'hp-pavilion-15' },
    { name: 'Canon EOS R50 Mirrorless Camera', brand: 'Canon', cat: 'Electronics', sub: 'Cameras', p: 67990, m: 75990, r: 4.6, rc: 890, slug: 'canon-eos-r50' },
    { name: 'iPad Air M2 11-inch', brand: 'Apple', cat: 'Electronics', sub: 'Tablets', p: 69900, m: 69900, r: 4.7, rc: 1543, slug: 'ipad-air-m2' },
    { name: 'Noise ColorFit Pro 5 Smartwatch', brand: 'Noise', cat: 'Electronics', sub: 'Smart Watches', p: 3499, m: 5999, r: 4.0, rc: 12340, slug: 'noise-colorfit-pro-5' },
    { name: 'JBL Charge 5 Bluetooth Speaker', brand: 'JBL', cat: 'Electronics', sub: 'Speakers', p: 12999, m: 15999, r: 4.5, rc: 4321, slug: 'jbl-charge-5' },
    { name: 'Allen Solly Men Polo T-Shirt', brand: 'Allen Solly', cat: 'Fashion', sub: 'T-shirts', p: 799, m: 1499, r: 4.1, rc: 9870, slug: 'allen-solly-polo' },
    { name: 'W Women Printed Kurta', brand: 'W', cat: 'Fashion', sub: 'Kurtas', p: 899, m: 1799, r: 4.3, rc: 5600, slug: 'w-printed-kurta' },
    { name: 'Fossil Men Analog Watch', brand: 'Fossil', cat: 'Fashion', sub: 'Watches', p: 7495, m: 12995, r: 4.4, rc: 3210, slug: 'fossil-analog-watch' },
    { name: 'Baggit Women Handbag', brand: 'Baggit', cat: 'Fashion', sub: 'Bags', p: 1899, m: 3599, r: 4.2, rc: 2340, slug: 'baggit-handbag' },
    { name: 'Milton Thermosteel Duo Flask', brand: 'Milton', cat: 'Home & Kitchen', sub: 'Appliances', p: 599, m: 1099, r: 4.4, rc: 22100, slug: 'milton-thermosteel-duo' },
    { name: 'Wakefit Orthopaedic Memory Foam Mattress', brand: 'Wakefit', cat: 'Home & Kitchen', sub: 'Bedding', p: 8999, m: 16999, r: 4.3, rc: 18700, slug: 'wakefit-ortho-mattress' },
    { name: 'Pigeon by Stovekraft Mixer Grinder', brand: 'Pigeon', cat: 'Home & Kitchen', sub: 'Appliances', p: 1799, m: 3495, r: 4.1, rc: 15600, slug: 'pigeon-mixer-grinder' },
    { name: 'Forest Essentials Soundarya Radiance Cream', brand: 'Forest Essentials', cat: 'Beauty', sub: 'Skincare', p: 2475, m: 2475, r: 4.5, rc: 1230, slug: 'forest-essentials-cream' },
    { name: 'L\'Oréal Paris Revitalift Crystal Micro-Essence', brand: 'L\'Oréal', cat: 'Beauty', sub: 'Skincare', p: 849, m: 999, r: 4.2, rc: 8900, slug: 'loreal-revitalift' },
    { name: 'Decathlon Domyos 10kg Dumbbells (Pair)', brand: 'Decathlon', cat: 'Sports', sub: 'Gym Equipment', p: 2499, m: 2999, r: 4.4, rc: 3400, slug: 'decathlon-dumbbells-10kg' },
    { name: 'Puma Men Running Shoes', brand: 'Puma', cat: 'Sports', sub: 'Sportswear', p: 2799, m: 4999, r: 4.2, rc: 6700, slug: 'puma-running-shoes' },
    { name: 'Atomic Habits by James Clear', brand: 'Penguin', cat: 'Books', sub: 'Self-Help', p: 325, m: 599, r: 4.7, rc: 67800, slug: 'atomic-habits' },
    { name: 'LEGO Classic Creative Brick Box', brand: 'LEGO', cat: 'Toys & Games', sub: 'LEGO/Building', p: 1999, m: 2999, r: 4.6, rc: 4500, slug: 'lego-classic-brick-box' },
    { name: 'Funskool Monopoly Board Game', brand: 'Funskool', cat: 'Toys & Games', sub: 'Board Games', p: 699, m: 1199, r: 4.3, rc: 8900, slug: 'monopoly-board-game' },
  ];

  items.forEach((item, idx) => {
    additional.push({
      id: `prod-${String(idx + 13).padStart(3, '0')}`,
      name: item.name,
      slug: item.slug,
      brand: item.brand,
      category: item.cat,
      subcategory: item.sub,
      price: item.p,
      mrp: item.m,
      rating: item.r,
      reviewCount: item.rc,
      image: `https://picsum.photos/seed/${item.slug}/400/400`,
      images: Array.from({ length: 5 }, (_, i) => `https://picsum.photos/seed/${item.slug}-${i + 1}/600/600`),
      badges: item.p < item.m * 0.7
        ? [{ text: `SALE -${Math.round(((item.m - item.p) / item.m) * 100)}%`, type: 'sale' as const }]
        : item.rc > 10000
          ? [{ text: 'BESTSELLER', type: 'bestseller' as const }]
          : [],
      freeDelivery: item.p > 999,
      inStock: true,
      isFulfilledByNexmart: idx % 3 === 0,
      description: `Discover the ${item.name} by ${item.brand}. This product delivers outstanding quality and performance at a competitive price. Designed with attention to detail and built to last, it meets the needs of discerning customers. Whether for personal use or as a gift, the ${item.name} is an excellent choice in the ${item.sub} category. Trusted by thousands of satisfied customers across India, this product has earned its reputation for reliability and value. Experience the difference that quality makes with ${item.brand}.`,
      shortDescription: `${item.name} by ${item.brand} — premium quality at great value.`,
      highlights: [
        `Premium ${item.brand} quality`,
        `Top rated in ${item.sub}`,
        'Fast delivery available',
        'Easy returns within 10 days',
        'Genuine product guaranteed',
      ],
      specs: {},
      manufacturingDetails: { countryOfOrigin: 'India' },
      vendorName: `${item.brand} Store`,
      vendorRating: 4.3 + Math.random() * 0.5,
    });
  });

  return additional;
}

// ── Mock Orders ────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  {
    id: 'ord-001',
    orderNumber: 'NM-K8F3D2-X7B9',
    status: 'DELIVERED',
    totalAmount: 134898,
    itemCount: 2,
    items: [
      { name: 'Samsung Galaxy S24 Ultra', image: 'https://picsum.photos/seed/samsung-s24/80/80', price: 129999, qty: 1 },
      { name: 'boAt Rockerz 450', image: 'https://picsum.photos/seed/boat-450/80/80', price: 1099, qty: 1 },
    ],
    createdAt: '2026-09-15T10:30:00Z',
    deliveredAt: '2026-09-18T14:20:00Z',
  },
  {
    id: 'ord-002',
    orderNumber: 'NM-R2T5H8-A3C6',
    status: 'SHIPPED',
    totalAmount: 4999,
    itemCount: 1,
    items: [
      { name: 'Nike Air Max 270 React', image: 'https://picsum.photos/seed/nike-airmax/80/80', price: 4999, qty: 1 },
    ],
    createdAt: '2026-09-20T16:45:00Z',
    awb: 'SR123456789',
    courier: 'Shiprocket',
    estimatedDelivery: '2026-09-24T18:00:00Z',
  },
  {
    id: 'ord-003',
    orderNumber: 'NM-P9W1J4-M6K2',
    status: 'PLACED',
    totalAmount: 2498,
    itemCount: 3,
    items: [
      { name: 'Prestige Kitchen Set', image: 'https://picsum.photos/seed/prestige-kitchen/80/80', price: 2499, qty: 1 },
    ],
    createdAt: '2026-09-22T09:15:00Z',
  },
];

// ── Mock User ─────────────────────────────────────────────────────────
export const MOCK_USER = {
  id: 'user-001',
  email: 'shreya@example.com',
  firstName: 'Shreya',
  lastName: 'Sharma',
  phone: '9876543210',
  avatar: 'https://picsum.photos/seed/user-shreya/80/80',
  role: 'CUSTOMER',
  addresses: [
    {
      id: 'addr-001',
      type: 'HOME',
      fullName: 'Shreya Sharma',
      phone: '9876543210',
      street: '42, Anna Nagar East, 3rd Street',
      landmark: 'Near VR Mall',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600102',
      isDefault: true,
    },
    {
      id: 'addr-002',
      type: 'WORK',
      fullName: 'Shreya Sharma',
      phone: '9876543210',
      street: 'Tidel Park, 4th Floor, Module 12',
      landmark: 'Taramani Link Road',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600113',
      isDefault: false,
    },
  ],
};

// ── Mock Reviews ──────────────────────────────────────────────────────
export const MOCK_REVIEWS = [
  {
    id: 'rev-001',
    rating: 5,
    title: 'Absolutely stunning phone!',
    body: 'The camera quality is unreal. Night mode is a game changer. Battery lasts all day even with heavy usage. The S Pen is so useful for quick notes. Best phone I\'ve ever owned!',
    user: { firstName: 'Rahul', lastName: 'M.' },
    isVerifiedPurchase: true,
    helpfulCount: 234,
    notHelpfulCount: 12,
    images: ['https://picsum.photos/seed/rev-1-1/200/200', 'https://picsum.photos/seed/rev-1-2/200/200'],
    createdAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'rev-002',
    rating: 4,
    title: 'Great phone, slightly heavy',
    body: 'Performance is top-notch and the display is gorgeous. Only downside is the weight — it\'s a big phone. But the features more than make up for it. Camera at 200MP is insane.',
    user: { firstName: 'Priya', lastName: 'K.' },
    isVerifiedPurchase: true,
    helpfulCount: 156,
    notHelpfulCount: 8,
    images: [],
    createdAt: '2026-09-08T15:30:00Z',
  },
  {
    id: 'rev-003',
    rating: 5,
    title: 'Worth every rupee',
    body: 'Upgraded from S22 Ultra and the difference is night and day. Galaxy AI features are genuinely useful. Circle to Search has changed how I use my phone. Highly recommend!',
    user: { firstName: 'Arjun', lastName: 'R.' },
    isVerifiedPurchase: true,
    helpfulCount: 89,
    notHelpfulCount: 3,
    images: ['https://picsum.photos/seed/rev-3-1/200/200'],
    createdAt: '2026-09-05T11:00:00Z',
  },
  {
    id: 'rev-004',
    rating: 3,
    title: 'Good but overpriced',
    body: 'It\'s a great phone but at this price point, I expected more innovation. The camera improvements over the S23 Ultra are marginal. Still, build quality is excellent and performance is smooth.',
    user: { firstName: 'Meena', lastName: 'S.' },
    isVerifiedPurchase: true,
    helpfulCount: 67,
    notHelpfulCount: 21,
    images: [],
    createdAt: '2026-09-01T09:45:00Z',
  },
];

// ── Footer Links ──────────────────────────────────────────────────────
export const FOOTER_LINKS = {
  company: [
    { label: 'About NexMart', href: '/about' },
    { label: 'Careers', href: '/careers' },
    { label: 'Press', href: '/press' },
    { label: 'Investor Relations', href: '/investors' },
    { label: 'Corporate Information', href: '/corporate' },
  ],
  help: [
    { label: 'Help Center', href: '/help' },
    { label: 'Track Your Order', href: '/track' },
    { label: 'Returns & Refunds', href: '/returns' },
    { label: 'Shipping Info', href: '/shipping' },
    { label: 'Contact Us', href: '/contact' },
  ],
  policy: [
    { label: 'Privacy Policy', href: '/privacy' },
    { label: 'Terms of Use', href: '/terms' },
    { label: 'Cookie Policy', href: '/cookies' },
    { label: 'Return Policy', href: '/return-policy' },
    { label: 'Grievance Redressal', href: '/grievance' },
  ],
  sell: [
    { label: 'Sell on NexMart', href: '/sell' },
    { label: 'Vendor Dashboard', href: '/vendor' },
    { label: 'Advertise', href: '/advertise' },
    { label: 'Partner with Us', href: '/partner' },
  ],
};

// ── Indian States ─────────────────────────────────────────────────────
export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Delhi', 'Chandigarh', 'Puducherry',
];

// ── Filter Options ────────────────────────────────────────────────────
export const FILTER_OPTIONS = {
  categories: ['Electronics', 'Fashion', 'Home & Kitchen', 'Beauty', 'Sports', 'Books', 'Toys & Games'],
  brands: ['Samsung', 'Apple', 'Nike', 'Sony', 'boAt', 'Levi\'s', 'Prestige', 'Mamaearth', 'OnePlus', 'HP', 'JBL', 'Puma', 'Wildcraft', 'Fossil', 'LEGO'],
  priceRanges: [
    { label: 'Under ₹500', min: 0, max: 500 },
    { label: '₹500 - ₹1,000', min: 500, max: 1000 },
    { label: '₹1,000 - ₹5,000', min: 1000, max: 5000 },
    { label: '₹5,000 - ₹20,000', min: 5000, max: 20000 },
    { label: '₹20,000 - ₹50,000', min: 20000, max: 50000 },
    { label: 'Over ₹50,000', min: 50000, max: Infinity },
  ],
  colors: [
    { name: 'Black', hex: '#1A1A1A' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Blue', hex: '#3B82F6' },
    { name: 'Red', hex: '#EF4444' },
    { name: 'Green', hex: '#10B981' },
    { name: 'Yellow', hex: '#F59E0B' },
    { name: 'Purple', hex: '#8B5CF6' },
    { name: 'Pink', hex: '#EC4899' },
    { name: 'Grey', hex: '#6B7280' },
    { name: 'Brown', hex: '#92400E' },
  ],
  sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
  ratings: [4, 3, 2, 1],
  sortOptions: [
    { value: 'relevance', label: 'Relevance' },
    { value: 'price_asc', label: 'Price: Low to High' },
    { value: 'price_desc', label: 'Price: High to Low' },
    { value: 'newest', label: 'Newest First' },
    { value: 'rating', label: 'Customer Rating' },
    { value: 'popularity', label: 'Popularity' },
  ],
};